### PR TITLE
make stream fields filterable

### PR DESCRIPTION
**Pull request by grzegorekb**

### CODE REVIEW

**Comment by grzegorekb** [comment]
the issue with `table filters being reset when new data arrives` is configurable in `ReactTable` library
https://react-table.tanstack.com/docs/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes

Grafanas' wrapper has the option turned off and doesn't allow to configure it. It will be easier I think to use `ReactTable` directly (without Grafana's wrapper) than to write custom filters. I will check what are the options for styling the table so it looks just like Grafana's component. Eventually, I can extract it from Grafanas code..

**Comment by niclash** [comment]
Also an option to change Grafana source code. I am already running a fork.

**Comment by grzegorekb** [comment]
Each change makes it more difficult to keep updates / merge. If it will not be too much effort using our own table component (even by copying Grafans code) I think it would be easier to maintain. It there will be some issues <- we always have this possibility to just modify Grafana code.

**Comment by niclash** [comment]
Agree!

**Comment by grzegorekb** [comment]
confirmed, that it's the intended behavior of Grafanas table:
https://github.com/grafana/grafana/issues/32913

**Pull request closed without merging**
